from enum import Enum
class Status(Enum):
    ALREADY_DOCX = 'ALREADY_DOCX'
    READY_TO_CONVERT = 'READY_TO_CONVERT'
    CONVERTING = 'CONVERTING'
    CONVERTED = 'CONVERTED'
    INVALID_EXTENSION = 'INVALID_EXTENSION'
    PDF_TOO_BIG = 'PDF_TOO_BIG'
    DOCX_TOO_BIG = 'DOCX_TOO_BIG'
    ERROR_WHILE_CONVERTING = 'ERROR_WHILE_CONVERTING'
    CHAPTERS_EXTRACTED = 'CHAPTERS_EXTRACTED'
    HTTP_ERROR = 'HTTP_ERROR'
